server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/home
    username: root
    password: rhksgh
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          dataSource:
            quartzDataSource:
              driver: org.mariadb.jdbc.Driver
              URL: jdbc:mariadb://localhost:3306/quartz
              user: root
              password: rhksgh
              provider: hikaricp
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: true
            tablePrefix: QRTZ_
            misfireThreshold: 60000
            clusterCheckinInterval: 1000
            isClustered: true
            dataSource: quartzDataSource
            acquireTriggersWithinLock: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

logging:
  level:
    root: info
    com:
      khpark0203:
        batch:
          service: debug
          client:  debug

external:
  goarch:
    baseurl: http://localhost:8000